In [1]:
from defaults import *
path_granular = '/orange/physics-dept/an.kandala/Biophysics_projeccts/granular_learner/granular_learner_ananth/granular_learner'
#append to PATH
sys.path.append(path_granular)
# from initialization import Granular_learner
# from energy_function import total_energy

In [ ]:
r1 = 1
r2 = 1.4*r1
Lx = 30
Ly = 15
inner_radii = [r1, r2]
prob = [0.4, 0.6]
#place input boundary spheres:
boundary_sphere_radius = 1
boundary_sphere_gap = 0 # gap between boundary spheres 
n_spheres = 50
learner = Granular_learner(Lx, Ly, inner_radii, boundary_sphere_radius, boundary_sphere_gap)
learner.initialize(n_spheres, prob)

In [ ]:
a = np.arange(20)
b = a
a += 4
print(b)

In [ ]:
def manual_distances(positions):
    """Compute the distances between each pair of particles.

    Parameters
    ----------
    positions : ndarray, shape (n_particles, n_dimensions)
        The positions of the particles.

    Returns
    -------
    distances : ndarray, shape (n_particles, n_particles)
        The distances between each particle pair.
    """
    n_particles, n_dimensions = positions.shape
    distances = np.zeros((n_particles, n_particles))
    for i in range(n_particles):
        for j in range(i + 1, n_particles):
            for k in range(n_dimensions):
                distances[i, j] += (positions[i, k] - positions[j, k])**2
            distances[i, j] = np.sqrt(distances[i, j])
            distances[j, i] = distances[i, j]
    return distances

def vectorized_distances(positions):
    """Compute the distances between each pair of particles.

    Parameters
    ----------
    positions : ndarray, shape (n_particles, n_dimensions)
        The positions of the particles.

    Returns
    -------
    distances : ndarray, shape (n_particles, n_particles)
        The distances between each particle pair.
    """
    differences = positions[:, np.newaxis, :] - positions[np.newaxis, :, :]
    distances = np.sqrt(np.sum(differences**2, axis=-1))
    return distances

In [ ]:
positions = np.random.uniform(size=(1000, 30))
radii = np.random.uniform(size=100)

# compare the performance of the two functions
%timeit manual_distances(positions)
%timeit vectorized_distances(positions)

  

In [ ]:
a = np.array([[j, 0, -1] for j in range(1,10)])
b = np.array([[100, 101, 102], [10, 11, 12]])
# pprint(a[:,:,np.newaxis])
#calculate the distance between particles in a and b
differences = a[:, np.newaxis, :] - b[np.newaxis, :, :]
print(differences.shape)
print(differences[2,1])
# print(differences[:,:,:])


In [ ]:

L   = 100       # simulation box dimension
N   = 4       # Number of particles
dim = 2 
r = (np.random.random(size=(N,dim))-0.5)*1.5*L
uti = np.triu_indices(N, k=1) 
print(uti)       
dr = r[uti[0]] - r[uti[1]]
print(dr)
# Minimum image distance of unwrapped dr
# dr -= L * np.round(dr/L)

print(dr)

In [ ]:
array = np.column_stack((np.arange(0,100), np.arange(0,100)))
mask = array == 2
print(array[mask])
# print(array)
print(np.sum(array[mask]))

In [ ]:
a = 10*np.random.uniform(size=(100))
L = 1
b = a%L
print(np.column_stack((a, b)))

In [26]:
a = np.random.uniform(size=(100, 100, 100 ))
b = np.column_stack((np.arange(100, 110), np.arange(101, 111)))
# a_ext = np.a[:, np.newaxis] 
print(a.shape)
print(a[:,:,:].shape) #a[:,:,0]

(100, 100, 100)
(100, 100, 100)


In [3]:
import numpy as np
r = np.arange(0, 10)
def func(r):
    r = r**2
    print(r)
    return np.sin(r)
print(r)
func(r)
print(r)

[0 1 2 3 4 5 6 7 8 9]
[ 0  1  4  9 16 25 36 49 64 81]
[0 1 2 3 4 5 6 7 8 9]


In [9]:
a = np.pi*np.arange(100000)
d = 5.12321234
%timeit a%d
# %timeit np.mod(a, d)
# %timeit a - d*np.floor(a/d)
# %timeit a - d*np.trunc(a/d)
# %timeit np.remainder(a, d)
%timeit a - d*np.round(a/d)


2.97 ms ± 3.45 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)
92.1 µs ± 124 ns per loop (mean ± std. dev. of 7 runs, 10,000 loops each)
